package modelo;
// Generated 11/10/2021 11:04:01 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Asignacion generated by hbm2java
 */
public class Asignacion  implements java.io.Serializable {


     private Integer idAsignacion;
     private Grupo grupo;
     private Laboratorio laboratorio;
     private Date fechaAsiganacion;

    public Asignacion() {
    }

    public Asignacion(Grupo grupo, Laboratorio laboratorio, Date fechaAsiganacion) {
       this.grupo = grupo;
       this.laboratorio = laboratorio;
       this.fechaAsiganacion = fechaAsiganacion;
    }
   
    public Integer getIdAsignacion() {
        return this.idAsignacion;
    }
    
    public void setIdAsignacion(Integer idAsignacion) {
        this.idAsignacion = idAsignacion;
    }
    public Grupo getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(Grupo grupo) {
        this.grupo = grupo;
    }
    public Laboratorio getLaboratorio() {
        return this.laboratorio;
    }
    
    public void setLaboratorio(Laboratorio laboratorio) {
        this.laboratorio = laboratorio;
    }
    public Date getFechaAsiganacion() {
        return this.fechaAsiganacion;
    }
    
    public void setFechaAsiganacion(Date fechaAsiganacion) {
        this.fechaAsiganacion = fechaAsiganacion;
    }

    //Dummy | + ", grupo=" + grupo + ", laboratorio=" + laboratorio |
    @Override
    public String toString() {
        return "Asignacion{" + "idAsignacion=" + idAsignacion + ", fechaAsiganacion=" + fechaAsiganacion + '}';
    }




}


