package modelo;
// Generated 11/10/2021 11:04:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Carrera generated by hbm2java
 */
public class Carrera  implements java.io.Serializable {


     private Integer idCarrera;
     private String nombreCarrera;
     private String facultad;
     private Set usuarios = new HashSet(0);

    public Carrera() {
    }

	
    public Carrera(String nombreCarrera, String facultad) {
        this.nombreCarrera = nombreCarrera;
        this.facultad = facultad;
    }
    public Carrera(String nombreCarrera, String facultad, Set usuarios) {
       this.nombreCarrera = nombreCarrera;
       this.facultad = facultad;
       this.usuarios = usuarios;
    }
   
    public Integer getIdCarrera() {
        return this.idCarrera;
    }
    
    public void setIdCarrera(Integer idCarrera) {
        this.idCarrera = idCarrera;
    }
    public String getNombreCarrera() {
        return this.nombreCarrera;
    }
    
    public void setNombreCarrera(String nombreCarrera) {
        this.nombreCarrera = nombreCarrera;
    }
    public String getFacultad() {
        return this.facultad;
    }
    
    public void setFacultad(String facultad) {
        this.facultad = facultad;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }

    //Dummy user | + ", usuarios=" + usuarios |
    @Override
    public String toString() {
        return "Carrera{" + "idCarrera=" + idCarrera + ", nombreCarrera=" + nombreCarrera + ", facultad=" + facultad + '}';
    }

}


