package modelo;
// Generated 11/10/2021 11:04:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Grupo generated by hbm2java
 */
public class Grupo  implements java.io.Serializable {


     private Integer idGrupo;
     private String nombreGrupo;
     private int cantidadIntegrantes;
     private String responsable;
     private Set asignacions = new HashSet(0);
     private Set usuarios = new HashSet(0);

    public Grupo() {
    }

	
    public Grupo(String nombreGrupo, int cantidadIntegrantes, String responsable) {
        this.nombreGrupo = nombreGrupo;
        this.cantidadIntegrantes = cantidadIntegrantes;
        this.responsable = responsable;
    }
    public Grupo(String nombreGrupo, int cantidadIntegrantes, String responsable, Set asignacions, Set usuarios) {
       this.nombreGrupo = nombreGrupo;
       this.cantidadIntegrantes = cantidadIntegrantes;
       this.responsable = responsable;
       this.asignacions = asignacions;
       this.usuarios = usuarios;
    }
   
    public Integer getIdGrupo() {
        return this.idGrupo;
    }
    
    public void setIdGrupo(Integer idGrupo) {
        this.idGrupo = idGrupo;
    }
    public String getNombreGrupo() {
        return this.nombreGrupo;
    }
    
    public void setNombreGrupo(String nombreGrupo) {
        this.nombreGrupo = nombreGrupo;
    }
    public int getCantidadIntegrantes() {
        return this.cantidadIntegrantes;
    }
    
    public void setCantidadIntegrantes(int cantidadIntegrantes) {
        this.cantidadIntegrantes = cantidadIntegrantes;
    }
    public String getResponsable() {
        return this.responsable;
    }
    
    public void setResponsable(String responsable) {
        this.responsable = responsable;
    }
    public Set getAsignacions() {
        return this.asignacions;
    }
    
    public void setAsignacions(Set asignacions) {
        this.asignacions = asignacions;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }

    //Dummy | + ", asignacions=" + asignacions + ", usuarios=" + usuarios
    @Override
    public String toString() {
        return "Grupo{" + "idGrupo=" + idGrupo + ", nombreGrupo=" + nombreGrupo + ", cantidadIntegrantes=" + cantidadIntegrantes + ", responsable=" + responsable + '}';
    }




}


