package modelo;
// Generated 11/10/2021 11:04:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Horario generated by hbm2java
 */
public class Horario  implements java.io.Serializable {


     private Integer idHorario;
     private String horaInicial;
     private String horaFinal;
     private String diasHabilitados;
     private Set laboratorios = new HashSet(0);

    public Horario() {
    }

	
    public Horario(String horaInicial, String horaFinal) {
        this.horaInicial = horaInicial;
        this.horaFinal = horaFinal;
    }
    
    public Horario(String horaInicial, String horaFinal, String diasHabilitados, Set laboratorios) {
       this.horaInicial = horaInicial;
       this.horaFinal = horaFinal;
       this.diasHabilitados = diasHabilitados;
       this.laboratorios = laboratorios;
    }
    
    public Horario(String horaInicial, String horaFinal, String diasHabilitados) {
       this.horaInicial = horaInicial;
       this.horaFinal = horaFinal;
       this.diasHabilitados = diasHabilitados;
    }
   
    public Integer getIdHorario() {
        return this.idHorario;
    }
    
    public void setIdHorario(Integer idHorario) {
        this.idHorario = idHorario;
    }
    public String getHoraInicial() {
        return this.horaInicial;
    }
    
    public void setHoraInicial(String horaInicial) {
        this.horaInicial = horaInicial;
    }
    public String getHoraFinal() {
        return this.horaFinal;
    }
    
    public void setHoraFinal(String horaFinal) {
        this.horaFinal = horaFinal;
    }
    public String getDiasHabilitados() {
        return this.diasHabilitados;
    }
    
    public void setDiasHabilitados(String diasHabilitados) {
        this.diasHabilitados = diasHabilitados;
    }
    public Set getLaboratorios() {
        return this.laboratorios;
    }
    
    public void setLaboratorios(Set laboratorios) {
        this.laboratorios = laboratorios;
    }

    //Dummy | + ", laboratorios=" + laboratorios |
    @Override
    public String toString() {
        return "Horario{" + "idHorario=" + idHorario + ", horaInicial=" + horaInicial + ", horaFinal=" + horaFinal + ", diasHabilitados=" + diasHabilitados + '}';
    }


}


