package modelo;
// Generated 11/10/2021 11:04:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Laboratorio generated by hbm2java
 */
public class Laboratorio  implements java.io.Serializable {


     private int idLaboratorio;
     private Horario horario;
     private String nombreLaboratorio;
     private String descripcionLaboratorio;
     private String imagenLaboratoiol;
     private byte habilitado;
     private Set asignacions = new HashSet(0);

    public Laboratorio() {
    }

	
    public Laboratorio(int idLaboratorio, Horario horario, String nombreLaboratorio, String descripcionLaboratorio, String imagenLaboratoiol, byte habilitado) {
        this.idLaboratorio = idLaboratorio;
        this.horario = horario;
        this.nombreLaboratorio = nombreLaboratorio;
        this.descripcionLaboratorio = descripcionLaboratorio;
        this.imagenLaboratoiol = imagenLaboratoiol;
        this.habilitado = habilitado;
    }
    
    public Laboratorio(int idLaboratorio, Horario horario, String nombreLaboratorio, String descripcionLaboratorio, String imagenLaboratoiol, byte habilitado, Set asignacions) {
       this.idLaboratorio = idLaboratorio;
       this.horario = horario;
       this.nombreLaboratorio = nombreLaboratorio;
       this.descripcionLaboratorio = descripcionLaboratorio;
       this.imagenLaboratoiol = imagenLaboratoiol;
       this.habilitado = habilitado;
       this.asignacions = asignacions;
    }
   
    public int getIdLaboratorio() {
        return this.idLaboratorio;
    }
    
    public void setIdLaboratorio(int idLaboratorio) {
        this.idLaboratorio = idLaboratorio;
    }
    public Horario getHorario() {
        return this.horario;
    }
    
    public void setHorario(Horario horario) {
        this.horario = horario;
    }
    public String getNombreLaboratorio() {
        return this.nombreLaboratorio;
    }
    
    public void setNombreLaboratorio(String nombreLaboratorio) {
        this.nombreLaboratorio = nombreLaboratorio;
    }
    public String getDescripcionLaboratorio() {
        return this.descripcionLaboratorio;
    }
    
    public void setDescripcionLaboratorio(String descripcionLaboratorio) {
        this.descripcionLaboratorio = descripcionLaboratorio;
    }
    public String getImagenLaboratoiol() {
        return this.imagenLaboratoiol;
    }
    
    public void setImagenLaboratoiol(String imagenLaboratoiol) {
        this.imagenLaboratoiol = imagenLaboratoiol;
    }
    public byte getHabilitado() {
        return this.habilitado;
    }
    
    public void setHabilitado(byte habilitado) {
        this.habilitado = habilitado;
    }
    public Set getAsignacions() {
        return this.asignacions;
    }
    
    public void setAsignacions(Set asignacions) {
        this.asignacions = asignacions;
    }

    //Dummy | + ", asignacions=" + asignacions + ", horario=" + horario + |
    @Override
    public String toString() {
        return "Laboratorio{" + "idLaboratorio=" + idLaboratorio + ", nombreLaboratorio=" + nombreLaboratorio + ", descripcionLaboratorio=" + descripcionLaboratorio + ", imagenLaboratoiol=" + imagenLaboratoiol + ", habilitado=" + habilitado + '}';
    }




}


