package modelo;
// Generated 11/10/2021 11:38:44 PM by Hibernate Tools 4.3.1
import java.util.HashSet;
import java.util.Set;
/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {
    
    private int idRol;
    private String nombreRol;
    private Set usuarios = new HashSet(0);
    
    public Rol() {
    }
    
    public Rol(int idRol, String nombreRol) {
        this.idRol = idRol;
        this.nombreRol = nombreRol;
    }
    
    public Rol(int idRol, String nombreRol, Set usuarios) {
       this.idRol = idRol;
       this.nombreRol = nombreRol;
       this.usuarios = usuarios;
    }
    
    public int getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(int idRol) {
        this.idRol = idRol;
    }
    
    public String getNombreRol() {
        return this.nombreRol;
    }
    
    public void setNombreRol(String nombreRol) {
        this.nombreRol = nombreRol;
    }
    
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }
    
    //Dummy por relacion con user
    @Override
    public String toString() {
        return "Rol{" + "idRol=" + idRol + ", nombreRol=" + nombreRol + '}';
    }
}