package modelo;
// Generated 11/10/2021 11:04:01 PM by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idUsuario;
     private Carrera carrera;
     private FormularioCovid formularioCovid;
     private Grupo grupo;
     private Rol rol;
     private String nombre;
     private String apellido;
     private String correo;
     private String celular;
     private String contrasena;
     private byte activo;
     private String imagenUsuario;
     private int semestre;

    public Usuario() {
    }

    public Usuario(int idUsuario, Carrera carrera, FormularioCovid formularioCovid, Grupo grupo, Rol rol, String nombre, String apellido, String correo, String celular, String contrasena, byte activo, String imagenUsuario, int semestre) {
       this.idUsuario = idUsuario;
       this.carrera = carrera;
       this.formularioCovid = formularioCovid;
       this.grupo = grupo;
       this.rol = rol;
       this.nombre = nombre;
       this.apellido = apellido;
       this.correo = correo;
       this.celular = celular;
       this.contrasena = contrasena;
       this.activo = activo;
       this.imagenUsuario = imagenUsuario;
       this.semestre = semestre;
    }
   
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Carrera getCarrera() {
        return this.carrera;
    }
    
    public void setCarrera(Carrera carrera) {
        this.carrera = carrera;
    }
    public FormularioCovid getFormularioCovid() {
        return this.formularioCovid;
    }
    
    public void setFormularioCovid(FormularioCovid formularioCovid) {
        this.formularioCovid = formularioCovid;
    }
    public Grupo getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(Grupo grupo) {
        this.grupo = grupo;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public byte getActivo() {
        return this.activo;
    }
    
    public void setActivo(byte activo) {
        this.activo = activo;
    }
    public String getImagenUsuario() {
        return this.imagenUsuario;
    }
    
    public void setImagenUsuario(String imagenUsuario) {
        this.imagenUsuario = imagenUsuario;
    }
    public int getSemestre() {
        return this.semestre;
    }
    
    public void setSemestre(int semestre) {
        this.semestre = semestre;
    }

    //Dummy | + ", carrera=" + carrera + ", formularioCovid=" + formularioCovid + ", grupo=" + grupo + ", rol=" + rol |
    @Override
    public String toString() {
        return "Usuario{" + "idUsuario=" + idUsuario + ", nombre=" + nombre + ", apellido=" + apellido + ", correo=" + correo + ", celular=" + celular + ", contrasena=" + contrasena + ", activo=" + activo + ", imagenUsuario=" + imagenUsuario + ", semestre=" + semestre + '}';
    }


}


